# Change these first
owner: bitnob # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Bitnob Website
    url: https://bitnob.com
    method: GET 
  
  - name: Bitnob API
    url: https://api.bitnob.co/health
    method: GET

  - name: Bitnob API docs 
    url: https://docs.bitnob.com/docs
    method: GET
  
  - name: Bitnob Dashboards
    url: https://app.bitnob.co
    method: GET

  - name: Hosted Checkout
    url: https://checkout.bitnob.co 
    method: GET 

  - name: Sandbox API 
    url: https://sandboxapi.bitnob.co/health 
    method: GET 

  - name: Sandbox Dashboards
    url: https://sandboxapp.bitnob.co 
    method: GET 

  - name: Sandbox Hosted Checkout 
    url: https://sandbox-checkout.bitnob.co/health
    method: GET 

  - name: Mobile App 
    url: https://api.bitnob.app
    method: GET 
assignees: # Users to assign downtime issues (optional)
  - NonsoAmadi10
  - ryder247
  - vincentayorinde
  - menimj
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # baseUrl: /uptime
  logoUrl: https://bitnob.com/wp-content/uploads/2021/04/logo-no-back-01.png
  favicon: https://bitnob.com/wp-content/uploads/2021/04/logo-no-back-01.png
  theme: dark
  cname: status.bitnob.com
  name: Bitnob
  introTitle: "**Bitnob** Enables You to Automatically Save in Bitcoin with as little as one dollar weekly starting Today. No Hustle, Easy, Secure and Profitable"
  introMessage: This is a status page which uses real-time data from our [GitHub repository](https://github.com/bitnob/uptime). 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
